language: node_js
node_js:
  - "stable"
cache:
  directories:
    - frontent/node_modules
script:
  - cd frontend
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontent/build
  on:
    branch: master
