language: node_js
node_js:
  - "stable"
cache:
  directories:
    - frontend/node_modules
before_script:
  - cd frontend
script:
  - yarn
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: master
